---
name: Omada Controller Stable
version: 5.13.3
slug: omada_controller_stable
description: TP-Link Omada Controller software
webui: https://[HOST]:[PORT:8043]
startup: application
arch:
  - aarch64
  - amd64
init: false
url: https://github.com/jkunczik/home-assistant-omada
map:
  - ssl
options:
  enable_hass_ssl: false
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.pem
schema:
  enable_hass_ssl: bool
  certfile: str
  keyfile: str
ports:
  8088/tcp: 8088
  8043/tcp: 8043
  8843/tcp: 8843
  29810/tcp: 29810
  29810/udp: 29810
  29811/tcp: 29811
  29811/udp: 29811
  29812/tcp: 29812
  29812/udp: 29812
  29813/tcp: 29813
  29813/udp: 29813
  29814/tcp: 29814
  29815/tcp: 29815
  29815/udp: 29815
  29816/tcp: 29816
  29816/udp: 29816
